### ISSUE TITLE
Missing column name in tableData

### ISSUE THREAD

**Issue by d-lach** [jamesdordoy/vue-datatable#10]
Hello, 

I have a problem with applying sort on my backend because of the lack of requested column name.
Currently, tableData sent to the server has the following fields:
`{
                length: this.perPage[0],
                search: '',
                column: 0,
                dir: 'asc',
                filters: this.filters
  }`

I think that the column_name/column_key field should be added either here or in the `getRequestPayload` getter. 
Without that, you have to work with columns order which is very prone to fail. Change of the rendering order of columns will break your backend functionality. 
With column_keys you can make your magic on the backend and leave frontend carefree. 

It is doable to relate Vue component which defines columns to the controller/repository with laravel blades but it's far from convenient. 

Let me know what do you think about it. Maybe there is some clever way to know by which field we should sort, which I haven't thought of so far?

**Comment by jamesdordoy** [comment]
Hello,

The sorting column name is sent to the back-end under the `column `key as you have shown above. Usually the key is sent as a string and i am surprised the column value looks to be a number as you have shown.

You can find more details [here](https://github.com/jamesdordoy/Laravel-Vue-Datatables). If you didn't see the other Repository containing the PHP package.

As for handling column sorting on the back-end. This could be very useful as it would also keep your sorting references separate from the component reducing code. Maybe defining these references in the Model would make most sense?

It would be great to get a PR with an example of how you would expect this to function.

Sorry maybe i am misunderstanding what you mean.

Thanks

**Comment by d-lach** [comment]
Thanks for a quick reply and for pointing that laravel-helper-repo I have overlooked it.
It's very helpful indeed, anyway I have deployed your package into my project (almost) successfully already :)

My concerns are precisely about line **183** of [DataTable.vue](https://github.com/jamesdordoy/vue-datatable/blob/master/src/components/DataTable.vue)

`this.tableData.column = this.getIndex(this.columns, 'name', key);`

and corresponding line **15** of [LaravelVueDatatableTrait](https://github.com/jamesdordoy/Laravel-Vue-Datatables/blob/master/src/Traits/LaravelVueDatatableTrait.php)

`$query = $query->orderBy(array_keys($columns)[$column], $orderBy);`

These two pieces of code show what I am talking about- namely, we are relying on the order of columns instead of their keys.
I would like to avoid specifying on the backend side what columns should/can exist on the frontend and I think this is what you are proposing in one of your examples (just found that):

`protected $dataTableColumns = [
        'id' => [
            'searchable' => false,
        ],
        'name' => [
            'searchable' => true,
        ],
        'email' => [
            'searchable' => true,
        ]
    ];`

I am not a fan of that mainly because of two reasons:
1) I will have to duplicate that on the frontend as well
2) why some backend guy (who is working on a model) should define how frontend is displaying data (I mean in what order)

Do you see my point? I would like to know what is the idea behind the current way of doing that back-front relation? :)

Also, I am wondering if what you said here:

> The sorting column name is sent to the back-end under the `column` key 

is correct? Because if so, then I do not understand how could that be? (according to above-mentioned lines of code)

I will give that a second thought because your answer and php helper-package shed new light on that. Possibly I will be able to make a quick PR tomorrow or stick to your convention in my project.

cheers! :)

**Comment by jamesdordoy** [comment]
Hey,

After checking over the repository again, you are correct the column index is sent to the back-end and not the column key. Yeah this isn't ideal and is a design flaw. I'll look to correct this with an update to the helper repo.

I do see your point now, duplicating the column reference in your model and component could be considered overkill. To shed a little light on the issue, my thought process was that not all columns may be searchable as the back-end developer may not have applied indexes to the columns and hadn't intended them to be searched on when the frontend user starts typing in the search input.

The front-end component `columns` array determines how the columns are ordered in the data table, if they are filterable etc. So there is a separation of concerns unless i'm not understanding your specific implementation?

Also setting the column reference in the model:
`protected $dataTableColumns = [ 'id' => [ 'searchable' => false, ], 'name' => [ 'searchable' => true, ], 'email' => [ 'searchable' => true, ] ];`

This is optional. This is used by the Trait to workout what columns can be searched on. Alternatively you can omit using this trait and do your own filtering on the data using the sent over request parameters. Just remember to paginate the results before using the `DataTableCollectionResource` :)

Hopefully this helps explain the purpose.

**Comment by jamesdordoy** [comment]
The backend column key index reference will be corrected in #11. 

Thanks for bring this to my attention!

Cheers 👍

**Comment by d-lach** [comment]
Great! 
Thanks for your work and quick fix :)

**Comment by jamesdordoy** [comment]
Corrected in `0.3.4`
