### ISSUE TITLE
Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by khyvez** [jamesdordoy/vue-datatable#12]
How can I fix this, Ive got error alert `TypeError: Cannot read property 'draw' of undefined`
here's the sample json url http://dummy.restapiexample.com/api/v1/employees I tried
![Screenshot from 2019-08-16 07-22-50](https://user-images.githubusercontent.com/8803979/63143422-c9f77600-bfb3-11e9-9440-097f712019be.png)
![Screenshot from 2019-08-16 07-23-25](https://user-images.githubusercontent.com/8803979/63143425-ca900c80-bfb3-11e9-96b4-9bdf9b325176.png)

**Comment by jamesdordoyneon** [comment]
Hey,

Having had a look at your [JSON listing](http://dummy.restapiexample.com/api/v1/employees). It looks like you may have missed the [Laravel Package](https://github.com/jamesdordoy/Laravel-Vue-Datatables) that is used with the component.

You will need to make use of the `DataTableCollectionResource` on your data as this will send the draw value back to the component. Hence why its undefined.

Let me know if this solves your problem.

**Comment by khyvez** [comment]
Perfectly fine now, thank you for the answer and thanks for this plugins, Great
