### ISSUE TITLE
How to disable the admin field

### ISSUE THREAD

**Issue by Javier1995** [jamesdordoy/vue-datatable#17]
![Captura](https://user-images.githubusercontent.com/11432889/63610520-46cfb480-c59f-11e9-8e17-3c23e7fe8d5c.PNG)

How Can I disable the active select?

**Comment by jamesdordoy** [comment]
Hey,

In your custom `DataTableFilters` component, remove the select in question.

**Comment by Javier1995** [comment]
ok another thing why do I get this error when I am typing on the search field TypeError: Cannot read property 'draw' of undefined

**Comment by Javier1995** [comment]
Please just give me a hint I have been looking for the error for a while. thanks

**Comment by jamesdordoy** [comment]
You may have missed this package [https://github.com/jamesdordoy/Laravel-Vue-Datatables](https://github.com/jamesdordoy/Laravel-Vue-Datatables), which is a Laravel helper package.

Otherwise, the draw value is sent by the table up to the backend and it is required that it is sent back with the response payload so the table knows that the response is for the current request.

Hopefully that solves your problem

**Comment by Javier1995** [comment]
I felt like it toke me like a year to re-write the filters. I did everything about the laravel-vue-datatables doc however, I have the error 500, I can't filter the datas by the search field. 


![Captura12](https://user-images.githubusercontent.com/11432889/63640547-3daa1a80-c667-11e9-8901-e8fc5b091ca3.PNG)
![Captura11](https://user-images.githubusercontent.com/11432889/63640553-44389200-c667-11e9-8d7f-f49b05950c0d.PNG)
![Captura](https://user-images.githubusercontent.com/11432889/63640555-47338280-c667-11e9-8a4a-f2fc50f1600e.PNG)

**Comment by Javier1995** [comment]
Any hint?

**Comment by jamesdordoy** [comment]
Hey,

Im not sure about the payload issue at the moment as i'm unable to replicate it.

Have you checked your error logs in regards to the 500 error? It may shed light on whats going wrong.

Thanks,

**Comment by ferdiebergado** [comment]
Hey Javier1995, perhaps you may have a datatable column that you declared in your model but it does not exist in your database, therefore, the search query fails. Just a guest.

**Comment by Javier1995** [comment]
This is actuallu what I got

![Captura](https://user-images.githubusercontent.com/11432889/64068212-75cad380-cbfa-11e9-80d6-fa874dbf654c.PNG)

**Comment by Javier1995** [comment]
> Hey Javier1995, perhaps you may have a datatable column that you declared in your model but it does not exist in your database, therefore, the search query fails. Just a guest.

All the columns were well-written, thanks

**Comment by Javier1995** [comment]
Guys I think it is the package option {
   ```
 "models": {
        "search_term": "The term used in each Model to declare if it is searchable by the Datatable"
    },
    "default_order_by": "The default order by Column on Page Loads"
}
```
But I don't know where to put it in

**Comment by Javier1995** [comment]
> Guys I think it is the package option {
> 
> ```
> "models": {
>      "search_term": "The term used in each Model to declare if it is searchable by the Datatable"
>  },
>  "default_order_by": "The default order by Column on Page Loads"
> }
> ```
> 
> But I don't know where to put it in

Well I put it in composer.json. and I had to clear cache and then republish the package so it worked well, filtered and everything until I got the error draw everytime I type. Its driving crazy Lol

**Comment by Javier1995** [comment]
> > Guys I think it is the package option {
> > ```
> > "models": {
> >      "search_term": "The term used in each Model to declare if it is searchable by the Datatable"
> >  },
> >  "default_order_by": "The default order by Column on Page Loads"
> > }
> > ```
> > 
> > 
> > But I don't know where to put it in
> 
> Well I put it in composer.json. and I had to clear cache and then republish the package so it worked well, filtered and everything until I got the error draw everytime I type. Its driving me crazy Lol

**Comment by jamesdordoy** [comment]
Run this in your terminal to publish the config options:

php artisan vendor:publish --provider="JamesDordoy\LaravelVueDatatable\Providers\LaravelVueDatatableServiceProvider"

**Comment by Javier1995** [comment]
Ok thanks it's working now! but I'd like to change the handling event keyup because when I type it takes some time and sometimes displays the error 500

**Comment by Javier1995** [comment]
Never mind guys! I'm gonna close this. Thank you so much. I'd introduce you to one of mexican girls but you are so far away Lol.

**Comment by Javier1995** [comment]
I needed to reopen this again :D I uninstalled the package and installed it again now the datas don't show up once the page is loaded, nevertherless, if I filter, they do. sorry for bothering you one more time, bro.

**Comment by Javier1995** [comment]
> I needed to reopen this again :D I uninstalled the package and installed it again now the datas don't show up once the page is loaded, nevertherless, if I filter, they do. sorry for bothering you one more time, bro.
> 
> //Loaded
> ![Captura](https://user-images.githubusercontent.com/11432889/64070146-87bf6d00-cc20-11e9-92fb-bd7c5e523d4b.PNG)
> 
> //filtering by numbers of items
> ![Captura](https://user-images.githubusercontent.com/11432889/64070157-afaed080-cc20-11e9-9265-b39603713a6f.PNG)

0.3.6 is okay for me.
