### ISSUE TITLE
Pass props to Component

### ISSUE THREAD

**Issue by aramirez92** [jamesdordoy/vue-datatable#8]
How can i pass row values to example component?

**Comment by jamesdordoy** [comment]
Hey,

In your example component, you are able to accept the `data` prop which corresponds to the row of data in question. This is automatically parsed to your component by default.

Try adding the following to your component:
``` js
props: {
    data: {
        type: Object,
        default: () => ({})
    }
},
```
By default, the row's data will be parsed as an object.

Let me know if that solves your issue.
