### ISSUE TITLE
axios headers not sent

### ISSUE THREAD

**Issue by 0xFACEC0DE** [jamesdordoy/vue-datatable#9]
Hello. When getting table data from laravel api with "middleware('auth:api')" in route i got 401 unauthorized, because auth headers from "window.axios.defaults.headers.common" object not sent by datatable.

How to make datatable component send that headers on each request?
Axios must send them by default, but in this case not.

**Comment by 0xFACEC0DE** [comment]
i solved this problem. for compatability with laravel auth:api middleware there must be 2 things:

window.axios.defaults.headers.common['Authorization'] = 'Bearer ' + api_token.content;
(just like with csrf token solution)

getRequestPayload() {
          .....
            return {
                params: payload,
                headers: {
                    ...window.axios.defaults.headers.common,   
          .........

**Comment by paolobattistella** [comment]
How have you solved? Where I need to do the suggested changes?

Thank you
Paolo

**Comment by 0xFACEC0DE** [comment]
add to client app entry file (app.js or bootstrap.js):
   const api_token = document.head.querySelector('meta[name="api-token"]');
   if (api_token.content) {
        window.axios.defaults.headers.common['Authorization'] = 'Bearer ' + api_token.content;
   }

also add to html (you need custom helper api_token() for this example):
    <meta name="api-token" content="{{ api_token() }}">

this issue is not about this package, its more about laravel auth case.

**Comment by jamesdordoy** [comment]
This is correct but would it be of help if you could parse additional config options and headers to the axios instance used by the datatable? As it is at the moment you are required to attach this header to the window which isn't ideal due to the overhead.

I am happy to push an update to add this functionality or alternatively either one or you are welcome to push a PR.

**Comment by TCURT15** [comment]
I'm running into this issue too. Needing to be able to pass an api token in the URL. Doesn't seem to be passing it no matter what way I try.
